### ISSUE TITLE
How to configure multinode with Authentication Enabled

### ISSUE THREAD

**Issue by jinnabaalu** [davidbkemp/advanced-elasticsearch-training#1]
We have configured three node cluster and deployed on AWS.

We have two issues

1. If one of the node goes down, some data is not showing up. 
2. When we enable Authentication and restart the elasticsearch it is not connecting to the elasticsearch

Please provide the docker-compose for three node cluster with Authentication enabled.

**Comment by davidbkemp** [comment]
Note: I am a representative of Elastic.
While you are welcome to look at the training material I post here, it comes with no guarantees and no support.

Having hopefully made that clear:

- I’m surprised you are missing data after losing one node. Are your indices replicated?
- I have had no experience with xpack security and so can’t offer any advice.

I suggest that you post your questions to the Elasticsearch discussion forum:
https://discuss.elastic.co/c/elasticsearch
