### ISSUE TITLE
how to set es7 cluster with multiple master nodes in docker compose?

### ISSUE THREAD

**Issue by nathan-zhu** [davidbkemp/advanced-elasticsearch-training#2]
Hi, i'm new for es7, but try to use cluster in docker-compose. but can't find way to setting multi master nodes in docker-compose, any idea? thanks.

**Comment by davidbkemp** [comment]
To make a node be “master eligible only”, you need to add additional settings under “environment”. Specifically:

```

environment:
 - node.master: true 
 -  node.data: false 
 -  node.ingest: false 
 -  cluster.remote.connect: false
```

The nodes you don’t want to be masters will need 

```
node.master: false
```

For more details, see 
https://www.elastic.co/guide/en/elasticsearch/reference/7.5/modules-node.html#master-node
and
https://www.elastic.co/guide/en/elasticsearch/reference/7.5/docker.html

If you are still stuck, can I please recommend that you post questions to
https://discuss.elastic.co/c/elasticsearch
